name = "my-nextjs-ssr-app"
compatibility_date = "2025-08-24"

[build]
  command = "npm run build"

[env.production]
  account_id = "your-cloudflare-account-id"
  workers_dev = false
  route = "your-production-route"
